### ISSUE TITLE
Correct Phpcs warnings

### ISSUE THREAD

**Issue by gunjanpatel** [gunjanpatel/joomla3-hello-world#14]
@dwarkeshsoni

FILE: ...ar/www/git/joomla3-hello-world/component/admin/controllers/category.php
--------------------------------------------------------------------------------
FOUND 4 ERROR(S) AFFECTING 4 LINE(S)
--------------------------------------------------------------------------------
  2 | ERROR | You must use "/**" style comments for a file comment
 27 | ERROR | Blank line found at start of control structure
 40 | ERROR | Blank line found after control structure
 41 | ERROR | Blank line found at end of control structure
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: /var/www/git/joomla3-hello-world/component/admin/models/category.php
--------------------------------------------------------------------------------
FOUND 2 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
  76 | ERROR | Closing parenthesis of a multi-line function call must be on a
     |       | line by itself
 223 | ERROR | Please consider an empty line before the return statement;
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: /var/www/git/joomla3-hello-world/component/admin/models/categories.php
--------------------------------------------------------------------------------
FOUND 3 ERROR(S) AFFECTING 3 LINE(S)
--------------------------------------------------------------------------------
 102 | ERROR | Functions and classes must not contain multiple empty lines in a
     |       | row; found 2 empty lines
 129 | ERROR | Blank line found after control structure
 130 | ERROR | Blank line found at end of control structure
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...ww/git/joomla3-hello-world/component/admin/views/category/tmpl/edit.php
--------------------------------------------------------------------------------
FOUND 7 ERROR(S) AFFECTING 4 LINE(S)
--------------------------------------------------------------------------------
 28 | ERROR | Blank line found at start of control structure
 30 | ERROR | Expected "if (...)\n"; found "if (...) "
 30 | ERROR | Blank line found at start of control structure
 32 | ERROR | Blank line found at end of control structure
 32 | ERROR | Closing brace must be on a line by itself
 41 | ERROR | Blank line found at end of control structure
 41 | ERROR | Closing brace must be on a line by itself
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...t/joomla3-hello-world/component/admin/views/categories/tmpl/default.php
--------------------------------------------------------------------------------
FOUND 26 ERROR(S) AFFECTING 13 LINE(S)
--------------------------------------------------------------------------------
  44 | ERROR | Expected "if (...)\n"; found "if (...) "
  44 | ERROR | Blank line found at start of control structure
  49 | ERROR | Blank line found at end of control structure
  49 | ERROR | Closing brace must be on a line by itself
  49 | ERROR | Blank line found at start of control structure
  51 | ERROR | Blank line found at end of control structure
  51 | ERROR | Closing brace must be on a line by itself
  56 | ERROR | Expected "if (...)\n"; found "if (...) "
  56 | ERROR | Blank line found at start of control structure
  60 | ERROR | Blank line found at end of control structure
  60 | ERROR | Closing brace must be on a line by itself
  60 | ERROR | Blank line found at start of control structure
  92 | ERROR | Each PHP statement must be on a line by itself
 101 | ERROR | Expected "if (...)\n"; found "if (...) "
 101 | ERROR | Blank line found at start of control structure
 113 | ERROR | Blank line found at end of control structure
 113 | ERROR | Closing brace must be on a line by itself
 114 | ERROR | Concat operator must be followed by one space
 114 | ERROR | Concat operator must be preceeded by one space
 115 | ERROR | Expected 1 space before "-"; 0 found
 115 | ERROR | Expected 1 space after "-"; 0 found
 116 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 126 | ERROR | Blank line found at end of control structure
 126 | ERROR | Closing brace must be on a line by itself
 129 | ERROR | Blank line found at end of control structure
 129 | ERROR | Closing brace must be on a line by itself
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: .../git/joomla3-hello-world/component/admin/views/categories/view.html.php
--------------------------------------------------------------------------------
FOUND 4 ERROR(S) AFFECTING 4 LINE(S)
--------------------------------------------------------------------------------
  98 | ERROR | Functions and classes must not contain multiple empty lines in a
     |       | row; found 2 empty lines
 112 | ERROR | No blank line found after control structure113 - 310
 136 | ERROR | Please put a space between the // and the start of comment text;
     |       | found "//'uc.name' =>
     |       | JText::_('COM_CONTACT_FIELD_LINKED_USER_LABEL'),"
 137 | ERROR | Please put a space between the // and the start of comment text;
     |       | found "//'c.access' => JText::_('JGRID_HEADING_ACCESS'),"
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: .../joomla3-hello-world/component/admin/views/helloworlds/tmpl/default.php
--------------------------------------------------------------------------------
FOUND 7 ERROR(S) AFFECTING 4 LINE(S)
--------------------------------------------------------------------------------
 53 | ERROR | Expected "if (...)\n"; found "if (...) "
 53 | ERROR | Blank line found at start of control structure
 63 | ERROR | Each PHP statement must be on a line by itself
 71 | ERROR | Blank line found at end of control structure
 71 | ERROR | Closing brace must be on a line by itself
 72 | ERROR | Blank line found at end of control structure
 72 | ERROR | Closing brace must be on a line by itself
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: .../git/joomla3-hello-world/component/admin/views/helloworld/tmpl/edit.php
--------------------------------------------------------------------------------
FOUND 3 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 21 | ERROR | Blank line found at start of control structure
 26 | ERROR | Blank line found at end of control structure
 26 | ERROR | Closing brace must be on a line by itself
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: /var/www/git/joomla3-hello-world/component/site/models/helloworld.php
--------------------------------------------------------------------------------
FOUND 8 ERROR(S) AFFECTING 8 LINE(S)
--------------------------------------------------------------------------------
  57 | ERROR | Please consider the /* */ style for comments that span over
     |       | multiple lines.
  61 | ERROR | Please consider the /* */ style for comments that span over
     |       | multiple lines.
  63 | ERROR | Whitespace found at end of line
  64 | ERROR | Whitespace found at end of line
  65 | ERROR | Whitespace found at end of line
  66 | ERROR | Please consider the /* */ style for comments that span over
     |       | multiple lines.
  69 | ERROR | Please consider the /* */ style for comments that span over
     |       | multiple lines.
 115 | ERROR | Blank line found at end of control structure
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...it/joomla3-hello-world/component/site/views/helloworld/tmpl/default.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 25 | ERROR | Tabs must be used to indent lines; spaces are not allowed
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

FILE: ...w/git/joomla3-hello-world/component/site/views/helloworld/view.html.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 30 | ERROR | Please put a space between the // and the start of comment text;
    |       | found "//		$this->msg        = $this->get('Msg');"
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

**Comment by dwarkeshsoni** [comment]
okay.
